services:
  - type: web
    name: bugsilla
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SMTP_URL
        sync: false
      - key: SMTP_FROM
        sync: false
